name: Node.js Package

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@adrianmg'
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GPR}}